### ISSUE TITLE
Создать HTTP ресурс с определёнными форматами ввода и вывода

### ISSUE THREAD

**Issue by Vanish404** [pub-t/name-to-point#1]

**Comment by Vanish404** [comment]
На вход string + базовая координата - json объект 
На выходе - преобразованное имя в координаты

**Comment by Vanish404** [comment]
Что отдать, когда наденных координат два или больше? Отдать все?
Что отдать, когда поиск объекта не дал ответа или объекта несуществует? Какой формат?

**Comment by irnc** [comment]
Макс, к кому адресованы эти вопросы?

**Comment by Vanish404** [comment]
> Макс, к кому адресованы эти вопросы?

Денису

**Comment by Vanish404** [comment]
Done #2, mb merge this pr?

**Comment by Vanish404** [comment]
Done, can we merge?
#2

**Comment by Vanish404** [comment]
Close, because we merge solution
